### ISSUE TITLE
AclNode::node() - Couldn't find Aros node identified by "Array ( [Aros0.model] => Users [Aros0.foreign_key] => 1 ) "

### ISSUE THREAD

**Issue by inimist** [ivanamat/cakephp3-aclmanager#20]
I installed aclmanager using composer. Then I ran `bin/cake acl_extras aro_sync`. It updated acos table. Now when i access AclManager in browser address bar it shows  : 

AclNode::node() - Couldn't find Aros node identified by "Array ( [Aros0.model] => Users [Aros0.foreign_key] => 1 ) "

I understand that we need to populate aro and aros_acos tables somehow but I am not sure how? If you could add a clear guide to make this plugin work it could save lot of time of developers. A nice plugin but with lack of proper install guide.

**Comment by raul338** [comment]
AFAIK At the moment there is no way to populate aros table from existing records. You have to start with an empty table....

**Comment by ivanamat** [comment]
Hi @inimist,

@raul338 is right, instead of obtaining the id of the first user for cases in which users already exist, at the moment all permissions are established to the user with id = 1.

Shortly I will do an update and I will get the first user id or I will put an option to select the user to whom you want to grant all the permissions.

Regards!

**Comment by yarkm13** [comment]
#29
